version: '3.8'
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /opt/wireguard-server/config:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/La_Paz
      - LOG_CONFS=true
      - ALLOWEDIPS=0.0.0.0/0
      - SERVERURL=auto
      - SERVERPORT=51820 
      - PEERS=10
      - PEERDNS=auto 
      - INTERNAL_SUBNET=192.168.80.0 